version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:sp622002@db:3306/blog_db
      - JWT_SECRET=c91cf30cc231e41cbbec8d96f87d17af2b045eea357241497182cdfe771e76c0
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=sp622002
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=corrin
      - MYSQL_PASSWORD=Sp622002@
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: